---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directories:
      - /tests
      - /etcdctl
      - /pkg
      - /tools/rw-heatmaps
      - /tools/testgrid-analysis
      - /etcdutl
      - /client/pkg
      - /client/v3
      - /client/internal/v2
      - /server
      - /api
      - /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    open-pull-requests-limit: 30
    groups:
      weekly-updates:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /tools/mod
    schedule:
      interval: daily
    allow:
      - dependency-type: direct
    groups:
      tools-mod:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /
    target-branch: "release-3.4"
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /
    target-branch: "release-3.5"
    schedule:
      interval: monthly
