---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directories:
      - "**/*"
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    open-pull-requests-limit: 30

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /
    target-branch: "release-3.4"
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /
    target-branch: "release-3.5"
    schedule:
      interval: monthly
