name: Bump Go version
on: pull_request
permissions:
  contents: write
  pull-requests: read
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'ivanvc/etcd'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@ffa630c65fa7e0ecfa0625b5ceda64399aea1b36 # v3.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Checkout the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: steps.metadata.outputs.directory == '/tools/container-images' && contains(steps.metadata.outputs.dependency-names, 'library/golang')
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - name: Update Go modules
        if: steps.metadata.outputs.directory == '/tools/container-images' && contains(steps.metadata.outputs.dependency-names, 'library/golang')
        run: |
          echo "${{steps.metadata.outputs.new-version}}" > .go-version
          make sync-toolchain-directive

          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

          find -name go.mod -exec git add {} \;
          git add go.work
          git diff --cached --quiet && exit 0

          git commit --signoff -m "build(deps): bump Go to ${{ steps.metadata.outputs.new-version }}."
          git push origin "HEAD:refs/heads/${{ github.event.pull_request.head.ref }}"
