---
name: Update Website on Release

on:
  release:
    types: [created]

jobs:
  update_website:
    name: Update website
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: ${{ secrets.ACTIONS_RUNNER_DEBUG == 'true' }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: "etcd-website",
              workflow_id: "update-release-version.yml",
              ref: "main",
              inputs: {
                release: context.payload.release.tag_name
              }
            });

#      - env:
#          RELEASE_TAG: ${{ github.event.release.tag_name }}
#        run: |
#          minor="$(echo $RELEASE_TAG | cut -d. -f1-2)"
#          sed -i 's/git_version_tag:\sv\([0-9]\+\.\)\{2\}[0-9]\+/git_version_tag: '$RELEASE_TAG'/' "content/en/docs/$minor/_index.md"
#          git add "content/en/docs/$minor/_index.md"
#          git -c user.name="$GITHUB_ACTOR" -c user.email="$GITHUB_ACTOR@users.noreply.github.com" commit -m "[$minor] Update installation version to latest tag ($RELEASE_TAG)"
#          git push origin main
