---
name: Reusable Robustness Workflow
on:
  workflow_call:
    inputs:
      etcdBranch:
        required: true
        type: string
      count:
        required: true
        type: number
      testTimeout:
        required: false
        type: string
        default: '30m'
      artifactName:
        required: true
        type: string
      runs-on:
        required: false
        type: string
        default: "['ubuntu-latest']"
      scenario:
        required: true
        type: string
      lazyfsEnabled:
        required: true
        type: boolean
permissions: read-all

jobs:
  test:
    # this is to prevent the job to run at forked projects
    if: github.repository == 'etcd-io/etcd'
    timeout-minutes: 210
    runs-on: ${{ fromJson(inputs.runs-on) }}
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}

      # Temporary monitoring to compare amd64 and arm64 runner performance
      # Refer: https://actuated.dev/blog/right-sizing-vms-github-actions
      - uses: alexellis/setup-arkade@b1816384b2260cfd2c023c6798d26075786cfc7f # v3
      - name: Install vmmeter
        run: |
          sudo -E arkade oci install ghcr.io/openfaasltd/vmmeter:latest --path /usr/local/bin/
      - uses: self-actuated/vmmeter-action@c7e2162e39294a810cab647cacc215ecd68a44f6 #v1

      - name: install-lazyfs
        if: ${{ inputs.lazyfsEnabled }}
        run: |
          sudo apt-get -o APT::Update::Error-Mode=any update && sudo apt-get --yes install cmake libfuse3-dev libfuse3-3 fuse3
          sudo sed -i 's/#user_allow_other/user_allow_other/g' /etc/fuse.conf
          make install-lazyfs
      - name: test-robustness
        env:
          ETCD_BRANCH: "${{ inputs.etcdBranch }}"
        run: |
          set -euo pipefail
          go clean -testcache

          GO_TEST_FLAGS="-v --count ${{ inputs.count }} --timeout ${{ inputs.testTimeout }} --run ${{ inputs.scenario }}"
          case "${ETCD_BRANCH}" in
            release-3.5)
              EXPECT_DEBUG=true GO_TEST_FLAGS=${GO_TEST_FLAGS} RESULTS_DIR=/tmp/results make test-robustness-release-3.5
              ;;
            release-3.4)
              EXPECT_DEBUG=true GO_TEST_FLAGS=${GO_TEST_FLAGS} RESULTS_DIR=/tmp/results make test-robustness-release-3.4
              ;;
            main)
              EXPECT_DEBUG=true GO_TEST_FLAGS=${GO_TEST_FLAGS} RESULTS_DIR=/tmp/results make test-robustness-main
              ;;
            *)
              echo "Failed to find target ${ETCD_BRANCH}"
              exit 1
              ;;
          esac
      - uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4.3.5
        if: always()
        with:
          name: ${{ inputs.artifactName }}
          path: /tmp/results/*
