---
name: Static Analysis
on: [push, pull_request]
permissions: read-all
jobs:
  module-dirs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list-modules.outputs.list }}
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - id: list-modules
      run: |
        echo ::set-output name=list::{\"modules\":[\"$(source ./scripts/test_lib.sh && module_dirs | sed 's/\s/","/g' )\"]}
  golangci:
    name: "Run golangci-lint on ${{ matrix.modules }}"
    runs-on: ubuntu-latest
    needs: module-dirs
    strategy:
      matrix: ${{ fromJSON(needs.module-dirs.outputs.matrix) }}
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - id: golangci-lint-version
        run: echo "version=$(cd tools/mod && go list -m -f {{.Version}} github.com/golangci/golangci-lint)" >> "$GITHUB_OUTPUT"
      - id: golangci-config
        run: echo "config=$(git rev-parse --show-toplevel)/tools/.golangci.yaml" >> "$GITHUB_OUTPUT"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@9d1e0624a798bb64f6c3cea93db47765312263dc # v5.1.0
        with:
          version: ${{ steps.golangci-lint-version.outputs.version }}
          args: --config=${{ steps.golangci-config.outputs.config }}
          working-directory: ${{ matrix.modules }}
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@"$(cd tools/mod && go list -m -f {{.Version}} github.com/golangci/golangci-lint)"
      - name: protoc
        uses: arduino/setup-protoc@149f6c87b92550901b26acd1632e11c3662e381f # v1.3.0
        with:
          version: '3.20.3'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          set -euo pipefail

          cargo install marker --version 0.9.0
      - run: |
          set -euo pipefail

          make verify
      - run: |
          set -euo pipefail

          make fix

          DIFF=$(git status --porcelain)

          if [ -n "$DIFF" ]; then
            echo "These files were modified:"
            echo
            echo "$DIFF"
            echo
            exit 1
          fi
